env:
  es2021: true
  node: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project: 'tsconfig.json'
plugins:
  - "@typescript-eslint/eslint-plugin"
  - "prettier"
root: true
ignorePatterns: ['.eslintrc.js']
rules:
  {
    max-len: ["error", { "code": 80 }],
    no-console: warn,
    no-debugger: warn,
    semi: ["error", "never"],
    "sort-imports":
      [
        "error",
        {
          "ignoreCase": true,
          "ignoreDeclarationSort": false,
          "ignoreMemberSort": false,
          "memberSyntaxSortOrder": ["all", "single", "multiple", "none"],
          "allowSeparatedGroups": true,
        },
      ],
    quotes: ["error", "single"],
    prettier/prettier: error,
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
  }